name: update numbers

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          sed -i 's/**<!--sizestart-->.*?<!--sizeend-->**/**<!--sizestart-->**$(du -BKB ${{ github.workspace }}/toki)<!--sizeend-->' ${{ github.workspace }}/README.md
